apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: restaurant-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: "mongodb+srv://nairuiliu:018213234Sh12%4095@clusterlab2.o3pwqmp.mongodb.net/?retryWrites=true&w=majority&appName=ClusterLab2"
            - name: JWT_SECRET
              value: "your_jwt_secret_key"
